version: '3'
services:
  api:
    build: .
    ports:
      - 8003:8888
    depends_on:
      - database
  database:
    container_name: 'database'
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=alamakota2
      - MYSQL_PASSWORD=alamakota
      - MYSQL_USER=mszupke
      - MYSQL_DATABASE=apidb
    ports:
      - 3366:3306