version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:16.0.1-jdk-buster

    working_directory: ~/hello-world-api

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - hello-world-api-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: hello-world-api-{{ checksum "pom.xml" }}

      # run tests
      - run: mvn test

      # package into a jar
      - run: mvn clean package

      # build and push docker image to docker hub
      - run: mvn clean compile

      # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: hello-world-api